### DISCUSSION TITLE
Docker/Nextcloud/Installation/

### DISCUSSION THREAD

**Discussion by giscus** [TrueBankai416/BankaiTechDocs#16] [Announcements]
# Docker/Nextcloud/Installation/

## Nextcloud Installation using Docker Compose

https://docs.bankai-tech.com/Nextcloud/Installation/Collabora

**Comment by TrueBankai416** [comment]
Hello!

**Comment by dexterdy** [comment]
If anyone finds this page and has any issues with 502 bad gateway errors, this might happen when your callabora server is behind a reverse proxy, so https and ssl are not handled by the server directly. Setting the following environment variable fixes that issue:

extra_params=value: --o:ssl.enable=false --o:ssl.termination=true

**Reply by TrueBankai416** [reply]
Examples:
1. If using environment files such as `.collabora.env`, you add the following to that `.env` file.
```
extra_params=--o:ssl.enable=false --o:ssl.termination=true
```

2. If using the environment inside of `docker-compose.yaml`
It would look something like
```
name: nextcloud

  services:
  collabora:
    container_name: collabora
    hostname: collabora
    privileged: true
    tty: true
    ports:
      - 9980:9980
    cap_add:
      - MKNOD
    image: collabora/code:latest
    environment:
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    restart: always
```
